export interface ZoneGame {
  id: number
  name: string
  genre: Array<string>
  steamUrl: string
  image: string
  actionText?: string,
  available?: boolean,
}

export const zonesGames: ZoneGame[] = [
  {
    id: 1,
    name: 'Beat Saber',
    genre: ['Rhythm', 'Action', 'Coop'],
    steamUrl: 'https://store.steampowered.com/app/620980/Beat_Saber/',
    image: 'beat_saber.jpg',
    actionText: 'LAUNCH',
    available: true,
  },
  {
    id: 2,
    name: 'The Blu',
    genre: ['Simulation'],
    steamUrl: 'https://store.steampowered.com/app/451520/The_Blu/',
    image: 'the_blu.jpg',
    actionText: 'DIVE',
    available: true,
  },
  {
    id: 3,
    name: 'Elven Assassin',
    genre: ['Coop', 'Action'],
    steamUrl: 'https://store.steampowered.com/app/503770/Elven_Assassin/',
    image: 'elven_assassin.jpg',
    actionText: 'DEPLOY',
    available: true,
  },
  {
    id: 4,
    name: 'Serious Sam 3: BFE',
    genre: ['Action', 'Shooter'],
    steamUrl: 'https://store.steampowered.com/app/567670/Serious_Sam_3_VR_BFE/',
    image: 'serious_sam.jpg',
    actionText: 'SHOOT',
    available: true,
  },
  {
    id: 5,
    name: 'Richie\'s Plank Experience',
    genre: ['Simulation'],
    steamUrl: 'https://store.steampowered.com/app/517160/Richies_Plank_Experience/',
    image: 'richies_plank.jpg',
    actionText: 'WALK',
    available: true,
  },
  {
    id: 6,
    name: 'Superhot VR',
    genre: ['Puzzle', 'Shooter'],
    steamUrl: 'https://store.steampowered.com/app/322500/SUPERHOT/',
    image: 'superhot.jpg',
    actionText: 'RUN',
    available: true,
  },
  {
    id: 7,
    name: 'Job Simulator',
    genre: ['Simulation'],
    steamUrl: 'https://store.steampowered.com/app/448280/Job_Simulator/',
    image: 'job_simulator.jpg',
    actionText: 'WORK',
    available: true,
  },
  {
    id: 8,
    name: 'Vacation Simulator',
    genre: ['Simulation'],
    steamUrl: 'https://store.steampowered.com/app/726830/Vacation_Simulator/',
    image: 'vacation_sim.jpg',
    actionText: 'RELAX',
    available: true,
  },
  {
    id: 9,
    name: 'Fruit Ninja VR',
    genre: ['Action'],
    steamUrl: 'https://store.steampowered.com/app/486780/Fruit_Ninja_VR/',
    image: 'fruit_ninja.jpg',
    actionText: 'SLICE',
    available: true,
  },
  {
    id: 10,
    name: 'Minecraft VR',
    genre: ['Coop', 'Survival', 'Adventure'],
    steamUrl: 'https://www.minecraft.net/',
    image: 'minecraft.jpg',
    actionText: 'BUILD',
    available: true,
  },
  {
    id: 11,
    name: 'Spider-Man: Far From Home',
    genre: ['Action', 'Adventure'],
    steamUrl: 'https://store.steampowered.com/app/1067800/SpiderMan_Far_From_Home_Virtual_Reality_Experience/',
    image: 'spiderman_ffh.jpg',
    actionText: 'SWING'
  },
  {
    id: 12,
    name: 'Rick and Morty: Virtual Rick-ality',
    genre: ['Adventure'],
    steamUrl: 'https://store.steampowered.com/app/469610/Rick_and_Morty_Virtual_Rickality/',
    image: 'rick_morty.jpg',
    actionText: 'WUBBA',
    available: true,
  },
  {
    id: 13,
    name: 'Among Us VR',
    genre: ['Coop'],
    steamUrl: 'https://store.steampowered.com/app/1849900/Among_Us_VR/',
    image: 'among_us.jpg',
    actionText: 'SUSPECT'
  },
  {
    id: 14,
    name: 'Cooking Simulator VR',
    genre: ['Simulation'],
    steamUrl: 'https://store.steampowered.com/app/1358140/Cooking_Simulator_VR/',
    image: 'cooking_sim.jpg',
    actionText: 'COOK',
    available: true,
  },
  {
    id: 15,
    name: 'Guns and Stories: Bulletproof VR',
    genre: ['Shooter'],
    steamUrl: 'https://store.steampowered.com/app/685690/GunsnStories_Bulletproof_VR/',
    image: 'guns_and_stories.jpg',
    actionText: 'DRAW',
    available: true,
  },
  {
    id: 16,
    name: 'Tilt Brush',
    genre: ['Simulator'],
    steamUrl: 'https://store.steampowered.com/app/327140/Tilt_Brush/',
    image: 'tilt_brush.jpg',
    actionText: 'PAINT',
    available: true,
  },
  {
    id: 17,
    name: 'Home - Spacewalk',
    genre: ['Simulation'],
    steamUrl: 'https://store.steampowered.com/app/512270/Home__A_VR_Spacewalk/',
    image: 'home_spacewalk.jpg',
    actionText: 'FLOAT',
    available: true,
  },
  {
    id: 18,
    name: 'Loco Dojo',
    genre: ['Coop'],
    steamUrl: 'https://store.steampowered.com/app/667800/Loco_Dojo/',
    image: 'loco_dojo.jpg',
    actionText: 'PLAY',
    available: true,
  },
  {
    id: 19,
    name: 'Blaston',
    genre: ['Shooter', 'Coop', 'Fighting'],
    steamUrl: 'https://store.steampowered.com/app/1427890/Blaston/',
    image: 'blaston.jpg',
    actionText: 'DUEL',
    available: true,
  },
  {
    id: 20,
    name: 'Creed: Rise to Glory',
    genre: ['Action', 'Coop', 'Fighting'],
    steamUrl: 'https://store.steampowered.com/app/804490/Creed_Rise_to_Glory/',
    image: 'creed.jpg',
    actionText: 'FIGHT'
  },
  {
    id: 21,
    name: 'Gorilla Tag',
    genre: ['Simulator'],
    steamUrl: 'https://store.steampowered.com/app/1533390/Gorilla_Tag/',
    image: 'gorilla_tag.jpg',
    actionText: 'CLIMB',
    available: true,
  },
  {
    id: 22,
    name: 'Pistol Whip',
    genre: ['Action', 'Shooter'],
    steamUrl: 'https://store.steampowered.com/app/1079800/Pistol_Whip/',
    image: 'pistol_whip.jpg',
    actionText: 'SHOOT',
    available: true,
  },
  {
    id: 23,
    name: 'Space Pirate Trainer',
    genre: ['Shooter', 'Action'],
    steamUrl: 'https://store.steampowered.com/app/418650/Space_Pirate_Trainer/',
    image: 'space_pirate.jpg',
    actionText: 'TRAIN',
    available: true,
  },
  {
    id: 24,
    name: 'Eagle Flight',
    genre: ['Simulation', 'Adventure'],
    steamUrl: 'https://store.steampowered.com/app/408250/Eagle_Flight/',
    image: 'eagle_flight.jpg',
    actionText: 'FLY',
    available: true,
  },
  {
    id: 25,
    name: 'GORN',
    genre: ['Action', 'Fighting'],
    steamUrl: 'https://store.steampowered.com/app/578170/GORN/',
    image: 'gorn.jpg',
    actionText: 'CRUSH',
    available: true,
  },
  {
    id: 26,
    name: 'Fancy Skiing 2',
    genre: ['Sports', 'Adventure'],
    steamUrl: 'https://store.steampowered.com/app/876930/Fancy_Skiing_2_Online/',
    image: 'fancy_skiing_2.jpg',
    actionText: 'SKI',
    available: true,
  },
  {
    id: 27,
    name: 'Hellsplit: Arena',
    genre: ['Horror', 'Action'],
    steamUrl: 'https://store.steampowered.com/app/1039880/Hellsplit_Arena/',
    image: 'hellsplit.jpg',
    actionText: 'SLAY',
    available: true,
  },
  {
    id: 28,
    name: 'Until You Fall',
    genre: ['Adventure', 'Action'],
    steamUrl: 'https://store.steampowered.com/app/858260/Until_You_Fall/',
    image: 'until_you_fall.jpg',
    actionText: 'RISE',
    available: true,
  },
  {
    id: 29,
    name: 'Drunkn Bar Fight',
    genre: ['Coop', 'Fighting'],
    steamUrl: 'https://store.steampowered.com/app/528550/Drunkn_Bar_Fight/',
    image: 'drunkn_bar.jpg',
    actionText: 'BRAWL',
    available: true,
  },
  {
    id: 30,
    name: 'Private Property',
    genre: ['Shooter'],
    steamUrl: 'https://store.steampowered.com/app/1481700/Private_Property/',
    image: 'private_property.jpg',
    actionText: 'DEFEND',
    available: true,
  },
  {
    id: 31,
    name: 'Arizona Sunshine',
    genre: ['Shooter', 'Coop', 'Adventure'],
    steamUrl: 'https://store.steampowered.com/app/342180/Arizona_Sunshine/',
    image: 'arizona_sunshine.jpg',
    actionText: 'SURVIVE',
    available: true,
  },
  {
    id: 32,
    name: 'Arizona Sunshine 2',
    genre: ['Shooter', 'Coop', 'Adventure'],
    steamUrl: 'https://store.steampowered.com/app/1540210/Arizona_Sunshine_2/',
    image: 'arizona_sunshine_2.jpg',
    actionText: 'SURVIVE',
    available: true,
  },
  {
    id: 33,
    name: 'After the Fall',
    genre: ['Shooter', 'Survival'],
    steamUrl: 'https://store.steampowered.com/app/751630/After_the_Fall/',
    image: 'after_the_fall.jpg',
    actionText: 'FREEZE',
    available: true,
  },
  {
    id: 34,
    name: 'The Walking Dead: Saints & Sinners',
    genre: ['Shooter', 'Survival'],
    steamUrl: 'https://store.steampowered.com/app/916840/The_Walking_Dead_Saints__Sinners/',
    image: 'walking_dead.jpg',
    actionText: 'SURVIVE',
    available: true,
  },
  {
    id: 35,
    name: 'Half-Life: Alyx',
    genre: ['Action', 'Adventure'],
    steamUrl: 'https://store.steampowered.com/app/546560/HalfLife_Alyx/',
    image: 'hla.jpg',
    actionText: 'ACTIVATE',
    available: true,
  },
  {
    id: 36,
    name: 'Boneworks & Bonelab',
    genre: ['Action', 'Adventure'],
    steamUrl: 'https://store.steampowered.com/app/823500/BONEWORKS/',
    image: 'boneworks.jpg',
    actionText: 'PHYSICS',
    available: true,
  },
  {
    id: 37,
    name: 'STRIDE',
    genre: ['Action', 'Shooter'],
    steamUrl: 'https://store.steampowered.com/app/1292040/STRIDE/',
    image: 'stride.jpg',
    actionText: 'RUN',
    available: true,
  },
  {
    id: 38,
    name: 'Breachers',
    genre: ['Shooter', 'Coop'],
    steamUrl: 'https://store.steampowered.com/app/1922010/Breachers/',
    image: 'breachers.jpg',
    actionText: 'BREACH',
    available: true,
  },
  {
    id: 39,
    name: 'SURV1V3',
    genre: ['Shooter', 'Survival'],
    steamUrl: 'https://store.steampowered.com/app/722180/SURV1V3/',
    image: 'surv1v3.jpg',
    actionText: 'ENDURE',
    available: true,
  },
  {
    id: 40,
    name: 'Pavlov VR',
    genre: ['Shooter', 'Coop'],
    steamUrl: 'https://store.steampowered.com/app/555160/Pavlov_VR/',
    image: 'pavlov.jpg',
    actionText: 'CONNECT',
    available: true,
  },
  {
    id: 41,
    name: 'PayDay 2 VR',
    genre: ['Action', 'Shooter', 'Coop'],
    steamUrl: 'https://store.steampowered.com/app/218620/PAYDAY_2/',
    image: 'payday2.jpg',
    actionText: 'HEIST',
    available: true,
  },
  {
    id: 42,
    name: 'Warhammer 40,000: Battle Sister',
    genre: ['Action', 'Shooter'],
    steamUrl: 'https://store.steampowered.com/app/1733890/Warhammer_40000_Battle_Sister/',
    image: 'warhammer_40k_bs.jpg',
    actionText: 'PURGE',
    available: true,
  },
  {
    id: 43,
    name: 'Phasmophobia',
    genre: ['Horror', 'Coop', 'Puzzle'],
    steamUrl: 'https://store.steampowered.com/app/739630/Phasmophobia/',
    image: 'phasmo.jpg',
    actionText: 'ENTER',
    available: true,
  },
  {
    id: 44,
    name: 'Propagation VR',
    genre: ['Horror', 'Action'],
    steamUrl: 'https://store.steampowered.com/app/1363430/Propagation_VR/',
    image: 'propagation.jpg',
    actionText: 'HIDE',
    available: true,
  },
  {
    id: 45,
    name: 'The Forest VR',
    genre: ['Horror', 'Survival'],
    steamUrl: 'https://store.steampowered.com/app/242760/The_Forest/',
    image: 'the_forest.jpg',
    actionText: 'CRAFT',
    available: true,
  },
  {
    id: 46,
    name: 'Forewarned',
    genre: ['Horror', 'Coop', 'Puzzle'],
    steamUrl: 'https://store.steampowered.com/app/1562420/FOREWARNED/',
    image: 'forewarned.jpg',
    actionText: 'ESCAPE',
    available: true,
  },
  {
    id: 47,
    name: 'Don\'t Knock Twice',
    genre: ['Horror'],
    steamUrl: '',
    image: 'dont_knock_twice.jpg',
    actionText: 'KNOCK',
    available: true,
  },
  {
    id: 48,
    name: 'Five Nights at Freddy\'s: Help Wanted',
    genre: ['Horror'],
    steamUrl: 'https://store.steampowered.com/app/732690/Five_Nights_at_Freddys_Help_Wanted/',
    image: 'fnaf.jpg',
    actionText: 'WATCH',
    available: true,
  }
]

// Оптимизированные категории (12 штук)
export const gameGenres = [
  'Все',
  'Action',
  'Shooter',
  'Horror',
  'Rhythm',
  'Puzzle',
  'Simulation',
  'Adventure',
  'Survival',
  'Sports',
  'Coop',
  'Fighting'
] as const

export type GameGenre = typeof gameGenres[number]

// Import and create a map of images
const images = import.meta.glob('/assets/images/games/library/zones/*.jpg', { eager: true });
const imageMap = Object.fromEntries(
  Object.entries(images).map(([key, value]) => {
    let path_items = key.split('/').pop()
    if (path_items) {
        const imageName = path_items.split('.')[0];
        return [imageName, value];
    }
    return [undefined, value]
  })
);

// Update image paths in zonesGames
zonesGames.forEach(game => {
  const imageName = game.image.replace('.jpg', '');
  if (imageMap[imageName]) {
    game.image = imageMap[imageName].default;
  }
});